clearance_system/clearance/urls.py
from django.urls import path, include
from . import views
app_name = 'clearance'

urlpatterns = [
    path('', views.clearances, name='request'),
    path('controlno/', views.controlNo, name='control_number'),
    path('registrar/clear/', views.clearStudent, name='registrar_clear'),
    path('search/student', views.searchStudent, name='search_student'),
]

clearance_system/clearance_system/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
import clearance
app_name = 'home'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('report',views.report,name='report'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('test/',views.test),
    path('requests/',include('clearance.urls')),
    path('department/',include('department.urls')),
    path('registrar/',views.registrar,name='registrar'),
    path('registrar/cleared/',views.registrarCleared,name='registrar_cleared')
]

clearance_system/department/urls.py
from django.urls import path,include
from . import views

app_name='departments'

urlpatterns = [
    path('',views.departments,name='departments'),
    path('requests',views.requests,name='department_requests'),
    path('items',views.items,name='department_items'),
    path('student_items',views.studentItems,name='student_items'),
    path('item/add',views.newItem,name='new_item'),
    path('item/borrow',views.borrowItem,name='borrow_item'),
    path('search/supervisor/student',views.searchStudent,name='search_student'),
    path('items/clear',views.clearItem,name='clear_item'),
    path('search/student/supervisor', views.searchStudentRequest,
         name='search_student_request'),
]

clearance_system/department/models.py
from accounts.models import CustomUser
from django.db import models
from accounts.models import Supervisor, Student

# Create your models here.


class Department(models.Model):
    dept_name = models.CharField(
        verbose_name='Department Name', name='dept_name', max_length=100)
    dept_head = models.ForeignKey(
        to=Supervisor, name='dept_hod', verbose_name='HOD', on_delete=models.PROTECT)
    is_academic = models.BooleanField(
        name='is_academic', verbose_name='Is Academic', default=False)

    def __str__(self) -> str:
        return self.dept_name + ' ' + str(self.dept_hod)

    class Meta:
        db_table = 'departments'
        verbose_name = 'Department'
        verbose_name_plural = "Departments"


class Items(models.Model):
    name = models.CharField(verbose_name='Item Name',
                            name='name', max_length=100)
    department = models.ForeignKey(
        to=Department, on_delete=models.PROTECT, name='item_dept', verbose_name='Department')
    price = models.IntegerField(verbose_name='price', name='price', default=0)
    Items = models.ManyToManyField(
        to=Student, through='StudentItems', related_name='student_items')

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = 'Item'
        verbose_name_plural = "Items"


class Course(models.Model):
    course_name = models.CharField(
        verbose_name='Course Name', name='name', max_length=200)
    dept = models.ForeignKey(
        to=Department, name='course_dept', on_delete=models.PROTECT)
    years_of_study = models.IntegerField(
        name='years', verbose_name='Years of Study')

    def __str__(self) -> str:
        return self.name + str(self.course_dept)

    class Meta:
        db_table = 'courses'
        verbose_name = 'Course'
        verbose_name_plural = 'Courses'


class StudentCourse(models.Model):
    course = models.ForeignKey(
        to=Course, name='course', on_delete=models.PROTECT)
    student = models.OneToOneField(
        to=Student, name='student', on_delete=models.PROTECT, unique=True)
    created = models.DateField(
        name='create_date', verbose_name='Createdd On', auto_now_add=True)

    class Meta:
        db_table = 'student_courses'
        verbose_name = 'Student Course'
        verbose_name_plural = 'Student Courses'


class StudentItems(models.Model):
    item = models.ForeignKey(
        to=Items, on_delete=models.PROTECT, name='student_item')
    student = models.ForeignKey(
        to=Student, on_delete=models.PROTECT, name='student')
    borrowed_on = models.DateField(
        name='borrow_date', verbose_name='Borrowed On', auto_now_add=True)
    returned_on = models.DateField(
        name='return_date', verbose_name='Returned On', null=True, blank=True)
    quantity = models.IntegerField(name='quantity', verbose_name='Quantity')

    @property
    def totalCost(self):
        return self.quantity * self.student_item.price

    class Meta:
        verbose_name = 'Student Item'
        verbose_name_plural = "Student Items"


class Report(models.Model):
    user = models.ForeignKey(
        to=CustomUser, on_delete=models.DO_NOTHING, name='user')
    message = models.CharField(
        verbose_name='message', name='message', max_length=255)
    email = models.EmailField(name='email', verbose_name='Email')
    created_at = models.DateTimeField(
        verbose_name='created_at', name='created_at', auto_now_add=True)
    updated_at = models.DateTimeField(
        verbose_name='updated_at', name='updated_at', auto_now=True)

    class Meta:
        db_table = 'reports'
        verbose_name = "Report"
        verbose_name_plural = "Reports"

    def __str__(self):
        return str(self.pk) + str(self.user) + self.email

clearance_system/department/forms.py
from django import forms
from department.models import Department, Items, StudentItems

class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ['dept_name','dept_hod']


class ItemsForm(forms.ModelForm):
    class Meta:
        model = Items
        fields = ['name','item_dept','price']


class StudentItemsForm(forms.ModelForm):
    class Meta:
        model = StudentItems
        fields = ['student_item','student','quantity']

clearance_system/department/views.py
from ntpath import join
from django.http import HttpResponse
from django.shortcuts import redirect, render
import datetime
from accounts.models import Student
from .models import Department, Items, StudentCourse, StudentItems
from .forms import ItemsForm, StudentItemsForm
from clearance.models import ClearanceRequests
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.template.defaulttags import register
from department.models import StudentCourse, Course
import requests as http


@register.filter
def get_item(dictionary, key):
    if type(dictionary.get(key)) == type([]):
        items = [item.name for item in dictionary.get(key)]
        val = ', '.join(items) + ' not returned'
        return val
    return dictionary.get(key)


@register.filter
def get_tuition_status(std_num):
    print(std_num)
    try:
        feeStat = http.get(
            'http://0.0.0.0:5000/student/{}'.format(std_num)).json()
        if feeStat['status']:
            return "Fully Paid"
        else:
            return "Due: {}".format(feeStat['due_amount'])
    except BaseException as e:
        return 'Not Found'


# Create your views here.


@login_required(login_url='/login')
def departments(request):
    course = StudentCourse.objects.get(student=request.user)
    deps = []
    academic_deps = Department.objects.filter(pk=course.course.course_dept.id)
    non_academic = Department.objects.filter(is_academic=False)

    for dep in academic_deps:
        deps.append(dep)
    for dep in non_academic:
        deps.append(dep)
    try:
        items = StudentItems.objects.filter(
            student=request.user, return_date=None)
    except StudentItems.DoesNotExist:
        items = []
    overdue_deps = [item.student_item.item_dept.id for item in items]
    return render(request, 'dashboard/departments.html', {'deps': deps, 'items': items, 'overdue': overdue_deps})


@login_required(login_url='/login')
def requests(request):
    print(request.user)
    dept = Department.objects.filter(dept_hod=request.user)
    items = Items.objects.filter(item_dept=dept[0])
    all_reqs = ClearanceRequests.objects.all()
    reqs = []
    if dept[0].is_academic:
        for req in all_reqs:
            std = Student.objects.get(pk=req.student.id)
            course = StudentCourse.objects.filter(student=std)[0]
            if course.course.course_dept.id == dept[0].id:
                reqs.append(req)
    else:
        reqs = ClearanceRequests.objects.all()
    print(reqs)
    pending_items_students = {}
    for req in reqs:
        print(type(req))
        student_items = StudentItems.objects.filter(
            student=req.student, return_date=None)
        if student_items:
            pending_items_students[req.student.id] = [
                item.student_item for item in student_items]
    return render(request, 'dashboard/supervisor_requests.html', {'reqs': reqs, 'items': items, 'dept': dept[0], 'pending_items': pending_items_students})


@login_required(login_url='/login')
def items(request):
    dept = Department.objects.filter(dept_hod=request.user)
    items = Items.objects.filter(item_dept=dept[0])
    return render(request, 'dashboard/supervisor_items.html', {'items': items})


@login_required(login_url='/login')
def studentItems(request):
    if request.POST:
        return HttpResponse('Post items')
    else:
        students = []
        dept = Department.objects.filter(dept_hod=request.user.id)[0]
        if dept.is_academic:
            courses = Course.objects.filter(course_dept=dept)
            print(courses)
            for course in courses:
                studs = StudentCourse.objects.filter(course=course)
                for stud in studs:
                    print(stud)
                    students.append(stud.student)
            std_items = [item for item in StudentItems.objects.all()
                         if item.student in students and item.student_item.item_dept == dept]
        else:
            std_items_all = StudentItems.objects.all()
            std_items = []
            for item in std_items_all:
                if item.student_item.item_dept.id == dept.id:
                    std_items.append(item)
            students = Student.objects.all()
        for itm in std_items:
            print(itm.student_item)
        dept_items = Items.objects.filter(item_dept=dept.id)

        return render(request, 'dashboard/supervisor_student.html', {'items': std_items, 'students': students, 'dept_items': dept_items})


@login_required(login_url='/login')
def newItem(request):
    if request.POST:
        name = request.POST.get('name')
        price = request.POST.get('price')
        dept = Department.objects.filter(dept_hod=request.user.supervisor)[0]
        item = Items.objects.create(name=name, item_dept=dept, price=price)
        item = item.save()
        messages.success(request, 'Item added successfully')
        return redirect('/department/items')


@login_required(login_url='/login')
def borrowItem(request):
    if request.POST:
        studentItemForm = StudentItemsForm(data=request.POST)
        if studentItemForm.is_valid():
            item = studentItemForm.save()
            messages.success(request, 'Record Saved succesfully')
            return redirect('/department/student_items')
        else:
            messages.error(request, 'An error occured')
            return redirect('/department/student_items')


@login_required(login_url='/login')
def searchStudent(request):
    if request.POST:
        query = request.POST.get('query')
        dept = Department.objects.filter(dept_hod=request.user)
        student = Student.objects.filter(std_number=query.replace(' ', ''))
        if student:
            student = student[0]
        else:
            return redirect('/search/supervisor/student')
        itemList = StudentItems.objects.filter(student=student[0])
        items = []
        for item in itemList:
            if item.student_item.item_dept == dept:
                items.append(item)
        return render(request, 'dashboard/supervisor_student.html', {'items': items})


@login_required(login_url='login/')
def clearItem(request):
    if request.POST:
        stdItem = request.POST.get('std_item')
        item = StudentItems.objects.get(pk=stdItem)
        item.return_date = datetime.date.today()
        item.save()
        return redirect('/department/student_items')


@login_required(login_url='/login')
def searchStudentRequest(request):
    if request.POST:
        query = request.POST.get('query')
        student = Student.objects.filter(std_number=query.replace(' ', '-'))[0]
        dept = Department.objects.filter(dept_hod=request.user)[0]
        if dept.is_academic:
            stdCourse = StudentCourse.objects.filter(student=student)
            if not stdCourse.course.dept == dept:
                return redirect('/supervisor/requests')
            else:
                student = ''
        reqs = ClearanceRequests.objects.filter(student=student)
        pending_items_students = {}
        for req in reqs:
            student_items = StudentItems.objects.filter(
                student=req.student, return_date=None)
            if student_items:
                pending_items_students[req.student.id] = [
                    item.student_item for item in student_items]
        return render(request, 'dashboard/supervisor_requests.html', {'reqs': reqs, 'pending_items': pending_items_students})

clearance_system/templates/dashboard/departments.html
{% extends 'dashboard_layout.html'%}

{% block body%}
<div class="container row">
 {% for dep in deps%}
     <div class="col-lg-4 m-2 mt-4 p-4 shadow">
         <span class="fs-4 fw-bold">
             {{ dep.dept_name}}
            </span><br>
            {{dep.dept_hod }}

            {% if dep.id in overdue %}
            <div class="col mt-4">
                    <div class="text-danger m-2">
                        <i class="icon ion-md-warning me-1" style="font-size: 18px;"></i>You have items due in this department
                    </div>
                <div class="h6">
                    Items Overdue:
                </div>
                <div class="row bg-light p-1">
                    <div class="col-5">
                        Item
                    </div>
                    <div class="col">
                        Quantity
                    </div>
                    <div class="col">
                        Amount
                    </div>
                </div>
                {% for item in items%}
                
                {% if item.student_item.item_dept.id == dep.id%}
                <div class="row p-1">
                    <div class="col-5">
                        {{ item.student_item  }}
                    </div>
                    <div class="col">
                        {{ item.quantity  }}
                    </div>
                    <div class="col">
                        {{ item.totalCost  }}
                    </div>
                </div>
                <div class="text-end me-4">
                    
                </div>

                {%endif %}
                {% endfor %}
            </div>
        {% else%}
        <div class="text-success mt-4">
            <i class="icon ion-md-checkmark-circle me-1" style="font-size: 18px;"></i>You are cleared in this department
        </div>
    {% endif %}

</div>
        {% endfor%}
    </div>

{% endblock %}

clearance_system/templates/dashboard/registrar.html
{% extends 'dashboard_layout.html'%}

{% block body%}
<div class="col">
    <div class="col-4 mt-3">
            
        {% if messages %}
        {% for message in messages %}
        {% if message.tags == 'success'%}
        <div class="alert alert-success" role="alert">
            <i class="icon ion-md-information-circle me-3" style="font-size: 24px;"></i> {{ message }}
        </div>
        {% elif message.tags == 'error'%}
        <div class="alert alert-danger" role="alert">
            <i class="icon ion-md-warning me-3" style="font-size: 24px;"></i> {{ message }}
        </div>
        {% endif %}
        {% endfor %}
        {% endif %}
    </div>
    <center>
    <form action="{% url 'clearance:search_student' %}"  method="post">
        {% csrf_token %}
        <div class="input-group mt-5">
            <div class="col-6 justify-content-center">
                <input type="search" class='col -6 form-control' placeholder='Search Student Number' name="query">
            </div>
                <input type="submit" class="input-group-text" value="Search"> 
        </div>
    </form>
    </center>


    <div class="col-10 h5 mt-5 ">
        Clearance Requests
    </div>
    <div class="row bg-light p-3">
        <div class="col">Reg No</div>
        <div class="col">Student Name</div>
        <div class="col">Date Requested</div>
        <div class="col">Status</div>
        <div class="col">Remarks</div>
        <div class="col">Actions</div>
    </div>
    {% if reqs%}
    {% for req in reqs%}
    <div class="row p-3">
        
        <div class="col">{{ req.student.std_number}}</div>
        <div class="col">{{ req.student}}</div>
        <div class="col">{{ req.requested_on}}</div>
        {% if req.status == 2%}
        <div class="col">
            <div class="col-6 text-white py-2 px-3 text-center rounded-pill bg-success">
                Cleared
            </div>
        </div>
        {% elif req.student.id not in pending_items.keys%}
        <div class="col">
            <div class="col-6 text-white py-2 px-3 text-center rounded-pill bg-success">
                Cleared
            </div>
        </div>
        {% else%}
        <div class="col">
            <div class="col-6 py-2 text-center px-3 rounded-pill text-white bg-danger">
                Pending
            </div>
        </div>
        {% endif%}
        {% if req.student.id in pending_items.keys%}
        <div class="col">
                <!-- {% for item in pending_items %} {{ pending_items }},{% endfor%} not returned -->
                {{ pending_items|get_item:req.student.id}}
        </div>
        {%else%}
        <div class="col">
            No Items in other departments
        </div>
        {% endif%}
        <div class="col">
            {% if req.status == 2 %}
            <button type="button" class="btn main-button">View</button>
            {% else %}
            <form action="{% url 'clearance:registrar_clear' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="req_id" value="{{req.id}}">
                <button type="submit" class="btn main-button">Clear</button>
            </form>
            {% endif%}
        </div>
    </div>
    {% endfor%}
    {%else%}
    <div class="text-center mt-4">
        No Requests
    </div>
    {% endif%}
</div>

{% endblock %}

clearance_system/templates/dashboard/student.html
{% extends 'dashboard_layout.html'%}
{% load static%}
{% block body%}
{% if user.student.student_status %}
    <div class="d-flex justify-content-center text-center ">
        <div class="p-5 mt-4">
            <div class="fs-3 pb-4">
                Congratulations, <span class="text-success">
                    {{ user }}
                </span> 
            </div>
            <img src="{% static 'images/undraw_certificate_re_yadi.svg'%}" height='300px' width='70%' alt="">
            <p class="pt-4 fs-3">
            You have completed your clearance.<br>
            </p>
            <p class="fs-4">
            Please visit <b>{{ sponsor }}</b> to receive your certificate

            </p>
        </div> 

    </div>
{% else%}
<div class="col justify-content-start">
    <center>

        <div class="col-4 mt-3">
            
            {% if messages %}
            {% for message in messages %}
            {% if message.tags == 'success'%}
            <div class="alert alert-success" role="alert">
                <i class="icon ion-md-information-circle me-3" style="font-size: 24px;"></i> {{ message }}
            </div>
            {% elif message.tags == 'error'%}
            <div class="alert alert-danger" role="alert">
                <i class="icon ion-md-warning me-3" style="font-size: 24px;"></i> {{ message }}
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}
        </div>
    </center>
    <div class="container mt-5 col p-3 fs-5 ">
        <div class="col-8">
        <div class="row bg-light p-3">

            <div class="col-3">
                <!-- <i class="icon ion-md-happy me-3" style="font-size: 72px;color:#030334"></i> -->
                {% if ClearanceRequest%}
                <img src="{% static 'images/undraw_done_re_oak4.svg'%}" width='90%' height='90%' alt="">
                {% else %}
                <img src="{% static 'images/undraw_choose_re_7d5a.svg'%}" width='90%' height='90%' alt="">
                {% endif%}
            </div>
            <div class="col-9 ">
                
               <b> Name: </b> &nbsp; {{ user }}. <br>
               <b> Course:</b>  &nbsp; {{ course.course.name }} <br>
               <b>  Department: &nbsp; </b> {{ dept.dept_name }} <br>


                {% if  ClearanceRequest  %}
                <p class="pt-3">
                    Your request was submitted on {{ ClearanceRequest.requested_on}}. Visit often to get the status of your request
                </p>
            {% else %}
            <p class="pt-3">

                You are currently not cleared for your certificate. To begin the process
                ,request for clearance.
            </p>
            <form action="{% url 'clearance:request'%}" class="pt-1" method="post">
                {% csrf_token %}
                <label for="supervisor" class="form-label fs-6 fw-light"> Choose your Sponsor: </label>
                <select name="supervisor" class="form-control">
                            {% for supervisor in supervisors%}
                            <option value="{{supervisor.id}}">{{ supervisor}}</option>
                            {% endfor%}
                </select>
                <input type="hidden" name="student" value="{{user.id}}">
                <input type='submit' class="btn  main-button active mt-4 px-3 py-2 fw-bold" value="Request Clearance">
            </form>
            {% endif %}
        </div>
    </div>
        </div>
            
    </div>
</div>

<div class="container mt-5">
    <p class="fs-4 fw-bold">My Items</p>
    <div class="row bg-light p-3">
            <div class="col">Item</div>
            <div class="col">Quantity</div>
            <div class="col">Borrowed Date</div>
            <div class="col">Returned Date</div>
            <div class="col">Status</div>
        </div>
    {% if items %}
    <div class="col">
        {% for item in items%}
                        <div class="row justify-content-center p-3 text-start">
                            <div class="col-3 text-start">{{ item.student_item}}</div>
                            <div class="col-2">{{ item.quantity}}</div>
                            <div class="col-3">{{ item.borrow_date}}</div>
                            <div class="col-3">{{ item.return_date}}</div>
                            {% if item.returned_on  %}
                            <div class=" col-auto py-2 px-3 rounded-pill bg-success">
                              Clear
                            </div>
                            {% else %}
                            <div class=" col-auto py-2 px-3 text-white rounded-pill bg-danger">
                                Due
                              </div>
                            {% endif%}
                        </div>
                        {% endfor%}

            <div class="col">

            </div>

       
    </div>
    {% else %}
    <p class="fs-5 p-2 text-center"> No items to dislay</p>
    {% endif%}

</div>

{% endif%}

{% endblock %}

clearance_system/templates/dashboard/supervisor_items.html
{% extends 'dashboard_layout.html'%}

{% block body%}
<div class="col">

  <div class="col-4 mt-3">
            
    {% if messages %}
    {% for message in messages %}
    {% if message.tags == 'success'%}
    <div class="alert alert-success" role="alert">
        <i class="icon ion-md-information-circle me-3" style="font-size: 24px;"></i> {{ message }}
    </div>
    {% elif message.tags == 'error'%}
    <div class="alert alert-danger" role="alert">
        <i class="icon ion-md-warning me-3" style="font-size: 24px;"></i> {{ message }}
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
</div>
    <div class="row p-3 d-flex justify-content-between">
        <div class="col-10 h5 ">
            Deparment Items
        </div>
        <div class="col">
            <!-- Button trigger modal -->
        <button type="button" class="btn main-button" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
            Add Item
        </button>
        </div>
    </div>
<div class="row bg-light p-3">
    <div class="col">
        Item Name
    </div>
    <div class="col">
        Price
    </div>
</div>

{% for item in items%}
<div class="row p-3">
    <div class="col">
        {{ item.name}}
    </div>
    <div class="col">
    {{ item.price}}
    </div>
</div>
{% endfor %}
</div>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Add Item</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form action="{% url 'departments:new_item'%}" method="post">
          {% csrf_token%}
          {{ dept }}
        <div class="modal-body">
              <div class=" mb-3 ">
                  <label for="name" class="form-label">Name:</label> 
                  <input type="text" name="name" class= ' form-control' id="name">
              </div>
              <div class="mb-3">
                    <label for="price" class="form-label">Price:</label> 
                  <input type="number" name="price" class='form-control' id="price">
              </div>

              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary bg-dark" data-bs-dismiss="modal">Close</button>
                <input type="submit" value="Add" class="btn main-button">
              </div>
            </form>
      </div>
    </div>
  </div>

{% endblock %}

clearance_system/templates/dashboard/supervisor_student.html
{% extends 'dashboard_layout.html'%}

{% block body%}
<div class="col mb-5">
    <div class="row p-3 d-flex justify-content-between">
      <form action="{% url 'departments:search_student'%}" method="post">
        {% csrf_token %}
        <div class="input-group m-3 mb-4">
          <div class="col-6 justify-content-center">
            <input type="search" name="query" class='col -6 form-control' placeholder='Search Student Number' name="search" id="">
          </div>
            <input type="submit" class="input-group-text" value="Search"> 
        </form>
    </div>
        <div class="col-10 h5 ">
            Borrrowed Items
        </div>
        <div class="col">
            <!-- Button trigger modal -->

        <button type="button" class="btn main-button" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
            Borrow Item
        </button>

        </div>
    </div>

    <div class="row bg-light p-3">
        <div class="col">Reg No</div>
        <div class="col-3 text-start">Student</div>
        <div class="col-2 text-start">Item</div>
        <div class="col-1 text-start">Quantity</div>
        <div class="col-2 text-start">Borrowed Date</div>
        <div class="col-2 text-start">Returned Date</div>
        <div class="col-1 text-start">Actions</div>
    </div>
    {% for item in items%}
                    <div class="row justify-content-center p-3 text-start">
                        <div class="col text-start">{{ item.student.std_number}}</div>
                        <div class="col-3 text-start">{{ item.student}}</div>
                        <div class="col-2 text-start">{{ item.student_item}}</div>
                        <div class="col-1 text-start">{{ item.quantity}}</div>
                        <div class="col-2 text-start">{{ item.borrow_date}}</div>
                        <div class="col-2 text-start">{{ item.return_date}}</div>
                        <div class="col-auto">
                          {% if not item.return_date%}
                          <form action="{% url 'departments:clear_item' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="std_item" value="{{ item.id}}">
                            <input type="submit" value="Clear" class="btn bg-warning">
                          </form>
                          {% else %}
                          <div class="btn  bg-success p-2 text-white">
                            Returned
                          </div>
                          {% endif%}
                        </div>
                    </div>
                    {% endfor%}   
</div>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Add Student</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form action="{% url 'departments:borrow_item'%}" method="post">
          {% csrf_token %}
        <div class="modal-body">
              <div class=" mb-3 ">
                  <label for="name" class="form-label">Student:</label> 
                  <select name="student" class="form-control">
                      <option value="">Select Student</option>
                      {% for stud in students%}
                      <option value="{{ stud.id}}"> {{ stud.std_number}} - {{ stud}}</option>
                      {% endfor %}
                  </select>
              </div>
              <div class="mb-3">
                    <label for="item" class="form-label">Item:</label> 
                  <!-- <input type="number" name="price" class='form-control' id="price"> -->
                  <select name="student_item" class="form-control">
                      <option value=""> Select Item</option>
                    {% for itm in dept_items%}
                    <option value="{{ itm.id}}"> {{ itm }}</option>
                    {% endfor %}
                </select>
              </div>
              <div class="mb-3">
                <label for="quantity" class="form-label">Quantity:</label> 
              <input type="number" name="quantity" class='form-control' id="price">
          </div>
                <input type="hidden" name="item_dept" value="{{dept.id}}">
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary bg-dark" data-bs-dismiss="modal">Close</button>
                <input type="submit" class="btn main-button">
              </div>
            </form>
      </div>
    </div>
  </div>

{% endblock%}