clearance_system/clearance/urls.py
from django.urls import path, include
from . import views
app_name = 'clearance'

urlpatterns = [
    path('', views.clearances, name='request'),
    path('controlno/', views.controlNo, name='control_number'),
    path('registrar/clear/', views.clearStudent, name='registrar_clear'),
    path('search/student', views.searchStudent, name='search_student'),
]

clearance_system/clearance_system/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
import clearance
app_name = 'home'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('report',views.report,name='report'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('test/',views.test),
    path('requests/',include('clearance.urls')),
    path('department/',include('department.urls')),
    path('registrar/',views.registrar,name='registrar'),
    path('registrar/cleared/',views.registrarCleared,name='registrar_cleared')
]

clearance_system/department/urls.py
from django.urls import path,include
from . import views

app_name='departments'

urlpatterns = [
    path('',views.departments,name='departments'),
    path('requests',views.requests,name='department_requests'),
    path('items',views.items,name='department_items'),
    path('student_items',views.studentItems,name='student_items'),
    path('item/add',views.newItem,name='new_item'),
    path('item/borrow',views.borrowItem,name='borrow_item'),
    path('search/supervisor/student',views.searchStudent,name='search_student'),
    path('items/clear',views.clearItem,name='clear_item'),
    path('search/student/supervisor', views.searchStudentRequest,
         name='search_student_request'),
]

clearance_system/templates/dashboard_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  {% include 'header.html' %}

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-2 pe-5   position-fixed h-100 main-button" id="sticky-sidebar" >
                <div class="row py-4">
                    <a class="navbar-brand fs-3 fw-bold color-text" href="#" style="color:#030334">
                       <img src="{% static 'images/cyborg-graduation-cap.png'%}" width='70' height='50' alt="">  OCS<br>
                    </a>
                </div>
                <ul class="nav flex-column justify-content-between sidebar list-group list-group-flush " >
                    <li class="nav-item list-group-item bg-transparent row mb-3 border-0">
                      <a class="nav-link " aria-current="page" href="{% url 'home'%}">
                        <i class="icon ion-md-home me-3" style="font-size: 24px;"></i> 
                           <b> Home</b>
                        </a>
                    </li>
                    {% if user.supervisor.is_supervisor%}
                    <li class="nav-item flex-row list-group-item bg-transparent row mb-3 border-0">
                      <a class="nav-link" href="{% url 'departments:department_requests' %}">
                        <i class="icon ion-md-clipboard me-3" style="font-size: 24px;"></i> 
                       <b> Requests</b>
                    </a>
                    </li>
                    {% endif %}
                    {% if user.registrar.is_registrar%}
                    <li class="nav-item flex-row list-group-item bg-transparent row mb-3 border-0">
                      <a class="nav-link" href="{% url 'registrar' %}">
                        <i class="icon ion-md-close-circle me-3" style="font-size: 24px;"></i> 
                       <b> Pending Requests</b>
                    </a>
                    </li>
                    <li class="nav-item flex-row list-group-item bg-transparent row mb-3 border-0">
                      <a class="nav-link" href="{% url 'registrar_cleared' %}">
                        <i class="icon ion-md-checkmark-circle me-3" style="font-size: 24px;"></i> 
                       <b> Cleared Requests</b>
                    </a>
                    </li>
                    {% endif %}
                    {% if not user.supervisor.is_supervisor%}
                      {% if not user.registrar.is_registrar%}
                    <li class="nav-item list-group-item bg-transparent mb-3 row border-0">
                        <a class="nav-link" href="{% url 'departments:departments' %}">
                                <i class="icon ion-md-business me-3" style="font-size: 24px;"></i> 
                               <b> Departments</b>
                            </a>
                    </li>
                    {% endif%}
                    {% endif%}
                    {% if user.supervisor.is_supervisor %}
                    <li class="nav-item list-group-item bg-transparent row mb-3 border-0">
                      <a class="nav-link" href="{% url 'departments:department_items' %}">
                        <i class="icon ion-md-pricetags me-3" style="font-size: 24px;"></i> 
                         <b> Items</b>
                        </a>
                    </li>
                    {% endif %}

                    {% if user.supervisor.is_supervisor %}
                    <li class="nav-item list-group-item bg-transparent row mb-3 border-0">
                      <a class="nav-link" href="{% url 'departments:student_items' %}">
                        <i class="icon ion-md-cart me-3" style="font-size: 24px;"></i> 
                         <b> Borrowed Items</b>
                        </a>
                    </li>
                    {% endif %}

                    <li class="nav-item list-group-item bg-transparent row mb-3 border-0">
                      <a class="nav-link" href="{% url 'report' %}">
                        <i class="icon ion-md-help-circle me-3" style="font-size: 24px;"></i> 
                         <b> Feedback</b>
                        </a>
                    </li>

                    </ul>
                    <div class=" bg-transparent border-0 justify-content-around position-absolute bottom-0 mb">
                           <div class="row mb-3 ">
                            <div class="col-auto fs-6 fw-light">
                              V 1.0.0
                            </div>
                            <div class="col-auto">

                      <!-- <a class="link" href="{% url 'report' %}">
                        <i class="icon ion-md-help-circle me-2" style="font-size: 20px;"></i> 
                          Feedback
                        </a> -->
                            </div>
                           </div> 
                            <!-- <a class="nav-link " href="{% url 'home' %}">
                                <i class="icon ion-md-medkit me-3" style="font-size: 24px;"></i> 
                                <b> Equipment</b>
                              </a> -->
                      </div>
            </div>
            <div class="col offset-2 w-90 " id="main" style="padding: 0px;">
                <nav class="navbar  main-bg ">
                    <div class="container-fluid">
                      <!-- <a class="navbar-brand" href="#">
                        <img src="{% static 'images/logo.jpeg' %}" alt="" width="50" height="50" class="d-inline-block align-text-center">
                        Title
                      </a> -->
                      <div class="col fs-3 fw-bold">
                       <!-- <input type="search" class="rounded-pill col-5 text-start border-0 px-3 py-2" placeholder='  Search Patient' name="search" id="search"> -->
                           <span>
                         Online Clearance System
                       </span>  
                      </div>
                      
                      <div class="d-flex flex-row justify-self-end  px-3  py-2 ">
                            {% if user.is_authenticated%}
                                <div class=" col-auto p-2 ">
                                 <div class="strong"><strong> {{ user }}</strong> </div>
                                 <div class="small"> 
                                    {{ user.getTitle}}
                                 </div>
                              </div> 
                              <div class="col-auto p-2">
                                <form action="{% url 'logout' %}" method="post">
                                  {% csrf_token %}
                                  <input type="submit" class='btn main-button  active px-3 py-2 fw-bold' value="Log Out">
                              </form>
                              </div>
                            {% else%}
                           
                            {% endif%}

                      </div>

                    </div>
                  </nav>
                  <!-- <div class="mt-4">
                    <div class="strong display-6 row col-8 justify-content-between">
                      <div class="col-6">
                        {% now "l\,\ d M Y"%}
                      </div>
                      <div class="col-3">
                        {% now "g\:i a"%}
                      </div>

                    </div>
                  </div> -->
                  <div class="px-3">
                {% block body %}
                    

                {%endblock %}
                  </div>

            </div>
        </div>
    </div>
   
    <script src="{% static 'bootstrap-5.1.3-dist/js/bootstrap.min.js' %}"></script>
    <script src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons.js"></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.10.2/main.min.js"></script> -->
    <script src="{% static 'scripts/main.js' %}"></script>
</body>
</html>

clearance_system/templates/header.html
{% load static%}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link href="https://unpkg.com/ionicons@4.5.10-0/dist/css/ionicons.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'bootstrap-5.1.3-dist/css/bootstrap.min.css' %}">
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.10.2/main.min.css"> -->
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
</head>

clearance_system/templates/login.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
{% include 'header.html'%}
<body>
    <nav class="navbar  p-3 main-bg">
        <div class="container-fluid">
          <!-- <a class="navbar-brand" href="#">
            <img src="{% static 'images/logo.jpeg' %}" alt="" width="50" height="50" class="d-inline-block align-text-center">
            Title
          </a> -->
          
          <div class="col fs-3">
            <img src="{% static 'images/cyborg-graduation-cap.png'%}" width='70' height='50' alt="">
            Online Clearance System
          </div>
          

        </div>
      </nav>
      <div class="container mt-5 pt-5 p-3 col-7 login-form">
          {% if form.errors %}
            <div class="alert alert-danger" role="alert">
         {{form.errors }}
            </div>

        {% endif %}
        <div class="row">
          <p class="fs-4 align-self-center text-center fw-bold"> Welcome to Online Clearance System</p>
        <div class="col">
            <img src="{% static 'images/undraw_graduation_re_gthn.svg'%}" height='100%' width='100%' alt="">
          </div>
            <form action="/login" method="post" class="col">
                {% csrf_token %}
                 <center>

        <div class="col mt-3">
            
            {% if messages %}
            {% for message in messages %}
            {% if message.tags == 'success'%}
            <div class="alert alert-success" role="alert">
                <i class="icon ion-md-information-circle me-3" style="font-size: 24px;"></i> {{ message }}
            </div>
            {% elif message.tags == 'error'%}
            <div class="alert alert-danger" role="alert">
                <i class="icon ion-md-warning me-3" style="font-size: 24px;"></i> {{ message }}
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}
        </div>
    </center>
                <div class="">
                    
                    {% block body%}
                    {% for field in form%}
                    
                    <div class=" mb-3">

                        <label for="email" class="form-label">{{ field.label }}</label>
                        {{ field|add_class:"form-control"}}
                        {{ field.error}}
                        
                    </div>
                    {% endfor %}
                    <div class="mb-3">
                      <label for="std-number" class="form-label">Reg No/Staff No:</label>
                      <input type="text" name="std-number" class="form-control" required>
                    </div>
                    <div class="mb-3">
                      <input type="checkbox" name="isStaff" class="form-check-input" >
                      <label for="isStaff">Log in as Staff</label>
                    </div>
                    {%endblock%} 
                </div>
                <div class="mb-5">
                    <input class='btn main-button m-3 active px-3 py-2 fw-bold' type="submit" value="Log In">
                </div>
            </form>
        </div>

            </div>
            
</body>
</html>

clearance_system/templates/test.html
{% extends 'dashboard_layout.html'%}

{% block body%}
{% for field in form%}
     {{ field.label }} <br>
     {{ field }}
 {% endfor %}
 {%endblock%}